services:
  postgres:
    image: postgres:17
    container_name: automotive-maintenance-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: automotive-maintenance
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/static/db/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
