server:
  servlet:
    context-path: /api-car

spring:
  profiles:
    active: ${MY_PROFILE_NAME}

  datasource:
    url: jdbc:postgresql://${HOST}:${PORT:5432}/${DB_NAME}?currentSchema=${SCHEMA}
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME}
    password: ${PASSWORD}
    hikari:
      minimum-idle: 2
      idle-timeout: 40000
      maximum-pool-size: 10
      connection-timeout: 10000
      keepalive-time: 30000
      schema: ${SCHEMA}

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        default_schema: ${SCHEMA:car_service}

    open-in-view: false
    show-sql: true

  threads:
    virtual:
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.yaml
    default-schema: ${SCHEMA:car_service}
    liquibase-schema: public

jwt:
  secret: ${JWT_SECRET:automotive-maintenance-jwt-signing-key-2026}
  access-exp: 3600000
  refresh-exp: 86400000